(() => {
  'use strict';
  const root = document.querySelector('#resubmission-root');
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
  const token = location.pathname.split('/').filter(Boolean).pop();
  const readFile = file => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1]); reader.onerror = reject; reader.readAsDataURL(file); });
  async function load() {
    const response = await fetch(`/api/application-resubmission/${encodeURIComponent(token)}`, { credentials: 'same-origin' });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) { root.innerHTML = `<section class="app-shell"><div class="app-content"><p class="app-eyebrow">Document request</p><h1>Link unavailable</h1><p>${esc(data.error || 'This document link is no longer available.')}</p><p class="app-supporting">Please contact the RRC leasing team for a new link.</p></div></section>`; return; }
    const submitted = new Set((data.documents || []).map(item => item.kind));
    const submittedDetails = Object.entries(data.details || {}).filter(([key, value]) => !['accuracy', 'previewAcknowledgement', 'typedName'].includes(key) && value !== '' && value !== false);
    const detailsHtml = submittedDetails.length ? `<section class="app-review-section"><h3>Application details already received</h3><dl class="review-grid">${submittedDetails.map(([key, value]) => `<div><dt>${esc(key.replace(/([A-Z])/g, ' $1').replace(/^./, char => char.toUpperCase()))}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl></section>` : '';
    root.innerHTML = `<section class="app-shell"><div class="app-layout"><aside class="app-sidebar"><p class="app-eyebrow">RRC leasing</p><h2>${esc(data.property.title)}</h2><p class="app-property-location">${esc(data.property.area)}</p><p class="app-sidebar-note">This private link is for your requested documents only.<br>It expires ${new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Manila' }).format(new Date(data.expiresAt))}.</p></aside><div class="app-content"><p class="app-eyebrow">Document request</p><h1>Complete your application documents</h1><p class="app-supporting">Hello ${esc(data.applicant.name)}. Your application details have been kept on file. Upload each document marked as required below.</p>${detailsHtml}<form novalidate>${data.requiredDocuments.map(kind => `<section class="app-document-card app-required-document"><h3>${esc(kind)} <span class="app-required">Required</span></h3><p>${submitted.has(kind) ? 'A file has already been received. You may upload a replacement if requested.' : 'This document is needed before RRC can complete its review.'}</p><label class="app-file-label">Choose PDF, JPG, or PNG<input type="file" data-document="${esc(kind)}" accept="application/pdf,image/jpeg,image/png,.pdf,.jpg,.jpeg,.png"></label><p class="app-field-error" data-error="${esc(kind)}"></p></section>`).join('')}<p class="app-error-summary" hidden></p><div class="app-form-actions"><span class="app-step-count">Files are uploaded securely to this application.</span><button class="btn btn-primary" type="submit">Submit documents</button></div></form></div></div></section>`;
    root.querySelector('form').addEventListener('submit', async event => {
      event.preventDefault(); const form = event.currentTarget; const files = [...form.querySelectorAll('[data-document]')].map(input => ({ kind: input.dataset.document, file: input.files[0], error: form.querySelector(`[data-error="${CSS.escape(input.dataset.document)}"]`) })); let invalid = false;
      files.forEach(item => { item.error.textContent = ''; if (!item.file) { item.error.textContent = 'This document is required.'; invalid = true; } else if (!['application/pdf', 'image/jpeg', 'image/png'].includes(item.file.type) || item.file.size > 5 * 1024 * 1024) { item.error.textContent = 'Use a PDF, JPG, or PNG no larger than 5 MB.'; invalid = true; } });
      if (invalid) return;
      const button = form.querySelector('button[type="submit"]'); button.disabled = true; button.textContent = 'Submitting documents…';
      try { for (const item of files) { const response = await fetch(`/api/application-resubmission/${encodeURIComponent(token)}/documents`, { method: 'POST', headers: { 'content-type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify({ kind: item.kind, fileName: item.file.name, mimeType: item.file.type, data: await readFile(item.file) }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || 'Could not upload your document.'); } root.innerHTML = `<section class="app-shell"><div class="app-content app-complete"><span class="app-complete-mark" aria-hidden="true">✓</span><p class="app-eyebrow">Documents received</p><h1>Thank you, your documents were submitted.</h1><p>RRC leasing has been notified and will continue the application review.</p></div></section>`; }
      catch (error) { const message = form.querySelector('.app-error-summary'); message.hidden = false; message.textContent = error instanceof Error ? error.message : 'Could not submit your documents.'; button.disabled = false; button.textContent = 'Submit documents'; }
    });
  }
  load();
})();
